services:
  php:
    build:
      context: ./.dockerfiles/php/
      dockerfile: Dockerfile
      args:
        user: alessandro
        uid: 1000
    container_name: travelonfly-php
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./www/backend:/var/www/backend
      - ./www/frontend:/var/www/html
    ports:
      - "6001:6001"
    networks:
      - travelonfly
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    container_name: travelonfly-mariadb
    ports:
      - "3307:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: MUpw@*56
      MYSQL_DATABASE: onfly
      MYSQL_USER: alessandro
      MYSQL_PASSWORD: MUpw@*56
    volumes:
      - ./.dockerfiles/database/:/var/lib/mysql
    networks:
      - travelonfly

  nginx:
    build:
      context: ./.dockerfiles/nginx
      dockerfile: Dockerfile
    container_name: travelonfly-nginx
    restart: unless-stopped
    ports:
      - "7080:7080"
      - "7090:80"
      - "5173:5173"
    volumes:
      - ./www/backend:/var/www/backend:ro
      - ./www/frontend:/var/www/html:ro
    networks:
      - travelonfly
    depends_on:
      - php

  redis:
    image: redis:latest
    container_name: travelonfly-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - travelonfly
    depends_on:
      - php

networks:
  travelonfly:
    driver: bridge

volumes:
  redis_data: